import type { Product } from '../types';

// Helper function to generate complete product objects
function createProduct(baseProduct: Partial<Product> & { id: string; name: string; price: number; category: string; description: string }): Product {
  const now = new Date().toISOString();
  return {
    ...baseProduct,
    slug: baseProduct.slug || baseProduct.name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, ''),
    currency: baseProduct.currency || 'BRL',
    stock_quantity: baseProduct.stock_quantity || 100,
    manage_stock: baseProduct.manage_stock || true,
    in_stock: baseProduct.in_stock !== false,
    image_url: baseProduct.image_url || baseProduct.image || 'https://placehold.co/300x300/ccc/000?text=No+Image',
    category_id: baseProduct.category_id || baseProduct.category || 'misc',
    status: baseProduct.status || 'published' as const,
    featured: baseProduct.featured || false,
    created_at: baseProduct.created_at || now,
    updated_at: baseProduct.updated_at || now,
    // Backward compatibility fields
    image: baseProduct.image || baseProduct.image_url,
    category: baseProduct.category,
    rating: baseProduct.rating,
    reviewCount: baseProduct.reviewCount,
    inStock: baseProduct.inStock !== false,
    originalPrice: baseProduct.originalPrice || baseProduct.sale_price
  } as Product;
}

export const MOCK_PRODUCTS: Product[] = [
  // PET
  createProduct({
    id: '1',
    name: 'Ração Premium para Cães',
    price: 89.99,
    sale_price: 89.99,
    originalPrice: 109.99,
    image: 'https://placehold.co/300x300/8b5cf6/ffffff?text=Racao+Cao',
    category: 'PET',
    category_id: 'pet',
    description: 'Ração premium com ingredientes naturais',
    rating: 4.8,
    reviewCount: 320,
    inStock: true,
  }),
  createProduct({
    id: '2',
    name: 'Brinquedo Interativo Gato',
    price: 34.99,
    image: 'https://placehold.co/300x300/f59e0b/ffffff?text=Brinquedo+Gato',
    category: 'PET',
    category_id: 'pet',
    description: 'Brinquedo que estimula o instinto natural',
    rating: 4.6,
    reviewCount: 185,
    inStock: true,
  }),
  // LATICÍNIOS
  createProduct({
    id: '3',
    name: 'Leite Integral 1L',
    price: 4.99,
    image: 'https://placehold.co/300x300/06b6d4/ffffff?text=Leite+1L',
    category: 'LATICÍNIOS',
    category_id: 'laticinios',
    description: 'Leite integral pasteurizado',
    rating: 4.5,
    reviewCount: 892,
    inStock: true,
  }),
  createProduct({
    id: '4',
    name: 'Queijo Mussarela 500g',
    price: 18.99,
    sale_price: 18.99,
    originalPrice: 22.99,
    image: 'https://placehold.co/300x300/eab308/ffffff?text=Queijo+500g',
    category: 'LATICÍNIOS',
    category_id: 'laticinios',
    description: 'Queijo mussarela fresco',
    rating: 4.7,
    reviewCount: 456,
    inStock: true,
  }),
  // MASSAS
  createProduct({
    id: '5',
    name: 'Macarrão Penne 500g',
    price: 3.49,
    image: 'https://placehold.co/300x300/dc2626/ffffff?text=Macarrao+Penne',
    category: 'MASSAS',
    category_id: 'massas',
    description: 'Macarrão de trigo durum',
    rating: 4.3,
    reviewCount: 234,
    inStock: true,
  }),
  createProduct({
    id: '6',
    name: 'Lasanha Pronta 400g',
    price: 12.99,
    image: 'https://placehold.co/300x300/059669/ffffff?text=Lasanha+400g',
    category: 'MASSAS',
    category_id: 'massas',
    description: 'Lasanha à bolonhesa congelada',
    rating: 4.4,
    reviewCount: 167,
    inStock: true,
  }),
  // DOCES
  createProduct({
    id: '7',
    name: 'Chocolate ao Leite 200g',
    price: 8.99,
    image: 'https://placehold.co/300x300/7c3aed/ffffff?text=Chocolate+200g',
    category: 'DOCES',
    category_id: 'doces',
    description: 'Chocolate cremoso ao leite',
    rating: 4.9,
    reviewCount: 678,
    inStock: true,
  }),
  createProduct({
    id: '8',
    name: 'Bala Mastigável Mix',
    price: 2.99,
    image: 'https://placehold.co/300x300/ec4899/ffffff?text=Bala+Mix',
    category: 'DOCES',
    category_id: 'doces',
    description: 'Mistura de balas mastigáveis',
    rating: 4.2,
    reviewCount: 123,
    inStock: true,
  }),
  // BEBIDAS
  createProduct({
    id: '9',
    name: 'Refrigerante Cola 2L',
    price: 6.49,
    sale_price: 6.49,
    originalPrice: 7.99,
    image: 'https://placehold.co/300x300/374151/ffffff?text=Refri+2L',
    category: 'BEBIDAS',
    category_id: 'bebidas',
    description: 'Refrigerante sabor cola',
    rating: 4.1,
    reviewCount: 445,
    inStock: true,
  }),
  createProduct({
    id: '10',
    name: 'Suco Natural Laranja 1L',
    price: 5.99,
    image: 'https://placehold.co/300x300/f97316/ffffff?text=Suco+1L',
    category: 'BEBIDAS',
    category_id: 'bebidas',
    description: 'Suco de laranja 100% natural',
    rating: 4.6,
    reviewCount: 287,
    inStock: true,
  }),
  // HIGIENE
  createProduct({
    id: '11',
    name: 'Pasta de Dente 90g',
    price: 4.99,
    image: 'https://placehold.co/300x300/10b981/ffffff?text=Pasta+90g',
    category: 'HIGIENE',
    category_id: 'higiene',
    description: 'Pasta de dente com flúor',
    rating: 4.4,
    reviewCount: 356,
    inStock: true,
  }),
  createProduct({
    id: '12',
    name: 'Sabonete Antibacteriano',
    price: 2.49,
    image: 'https://placehold.co/300x300/3b82f6/ffffff?text=Sabonete+Anti',
    category: 'HIGIENE',
    category_id: 'higiene',
    description: 'Sabonete líquido antibacteriano',
    rating: 4.7,
    reviewCount: 234,
    inStock: true,
  }),
];

export const SHELF_CATEGORIES = [
  {
    id: 'smartphones',
    name: 'Smartphones',
    title: 'Smartphones em Oferta',
  },
  {
    id: 'notebooks',
    name: 'Notebooks', 
    title: 'Notebooks Para Trabalho',
  },
  {
    id: 'tablets',
    name: 'Tablets',
    title: 'Tablets Para Criatividade',
  },
  {
    id: 'moda',
    name: 'Moda',
    title: 'Tendências da Moda',
  },
];